language: node_js
node_js:
  - node
sudo: false

script:
  - npm install -g nws
  - npm install
  # - nws -d dist -o

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ./dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
